// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pupper.Models;

namespace pupper.Migrations
{
    [DbContext(typeof(PupperContext))]
    partial class PupperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pupper.Models.Doggo", b =>
                {
                    b.Property<int>("DoggoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PicUrl");

                    b.HasKey("DoggoId");

                    b.ToTable("Doggos");

                    b.HasData(
                        new
                        {
                            DoggoId = 1,
                            Age = 7,
                            Breed = "Mutt",
                            Gender = "Female",
                            Name = "Matilda",
                            PicUrl = "https://t1.ea.ltmcdn.com/en/images/4/0/0/small_white_dog_breeds_3004_600.jpg"
                        },
                        new
                        {
                            DoggoId = 2,
                            Age = 11,
                            Breed = "Dachshund",
                            Gender = "Male",
                            Name = "Bagera",
                            PicUrl = "https://i.pinimg.com/originals/0c/dc/6b/0cdc6b9ea47cdee8ff88c1d6c9e02ca7.jpg"
                        },
                        new
                        {
                            DoggoId = 3,
                            Age = 2,
                            Breed = "Mutt",
                            Gender = "Male",
                            Name = "Flash",
                            PicUrl = "https://www.sciencesource.com/Doc/TR1_WATERMARKED/0/f/c/f/SS2695389.jpg?d63644087851"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
